version: "3"

networks:
  traefik:
    external: true
  internal:
    external: false

services:
  public_audio:
    image: node:carbon
    command: bash -c "npm install && npx gulp serve"
    working_dir: "/home/node"
    volumes:
      - './:/home/node/:cached'
    networks:
      - traefik
      - internal
    labels:
      - "traefik.backend=hfocus"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:kwego.txto.com.br"
      - "traefik.enable=true"
      - "traefik.port=9876"
    environment:
      HOST: 0.0.0.0
      PORT: 9876
