version: "3"

networks:
  traefik:
    external: true
  internal:
    external: false

services:
  kwego:
    build: .
    command: bash -c "npm install && npx gulp serve"
    networks:
      - traefik
      - internal
    labels:
      - "traefik.backend=kwego"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.rule=Host:kwego.txto.com.br"
      - "traefik.enable=true"
      - "traefik.port=9876"
    environment:
      HOST: 0.0.0.0
      PORT: 9876
